
CREATE TABLE IF NOT EXISTS muzzmaindb.matches(
	id INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
    user1_id BINARY(16),
    user1_id BINARY(16),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB;