CREATE TABLE IF NOT EXISTS muzzmaindb.users(
	  id INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
    uuid BINARY(16) NOT NULL,
    email VARCHAR(320) NOT NULL,
    password_hash CHAR(60) NOT NULL,
    name VARCHAR(100) NOT NULL,
    gender VARCHAR(10) NOT NULL,
    age INT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB;